"""
This test is supposed to be run after callgraphs have been generated by scripts/run_doxygen.py
"""

import subprocess
import sys
import os

src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../src"))
sys.path.insert(0, src_path)
from merge_callgraphs import merge_dot_files_enhanced
from function_relationships import get_relationship_text, load_function_graph
from config import *


if __name__ == "__main__":
    
    # Check if Doxyfile exists in the current directory, otherwise use provided path.
    dir_path = DIR_PATH
    doxygen_html_path = os.path.join(dir_path,"html")

    json_path = os.path.join(doxygen_html_path,"merged_graph.json")
 
    graph = load_function_graph(json_path)
    function_name = "SiWidthCnv_p1::persToTrans"
    relationship_text = get_relationship_text(function_name, graph)
    print(function_name, relationship_text)

    function_name = "InDetPerfPlot_Hits::fill"
    relationship_text = get_relationship_text(function_name, graph)
    print(function_name, relationship_text)
