import sys
import os
import logging
import click
import torch
import time

celloai_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../src"))
sys.path.insert(0, celloai_path)

from prompt_template import doxygen_system_prompt
from llamacpp_request import openai_nonstream
from retrieval_pipeline import get_text_embeddings, get_code_embeddings, CHROMA_SETTINGS
from function_relationships import get_function_relationships, load_function_graph
from langchain_chroma.vectorstores import Chroma
from chromadb.config import Settings
CHROMA_SETTINGS = Settings(
    anonymized_telemetry=False,
    is_persistent=True,
)

import re
import glob
import numpy as np

from extract import extract_cpp_functions, extract_cpp_function_names_params_returns
from write import remove_comment_block_init_end
from retrieval_pipeline import retrieval_qa_pipline_with_logging
from prompt_template import doxygen_function_prompt, doxygen_system_prompt
from sklearn.feature_extraction.text import CountVectorizer
NUM_CODE = 10
NUM_TEXT = 10

HOST = "localhost"
PORT = 8002
MAX_TOKENS = 8192
TEMPERATURE = 0.5
RAG = True 
#pattern = "<|start|>assistant<|channel|>final<|message|>"
pattern = ""
url = f"http://{HOST}:{PORT}/v1/chat/completions"

def common_ngrams(text1, text2, n=2):
    vec = CountVectorizer(ngram_range=(n, n), analyzer="word").fit([text1, text2])
    grams1 = set(vec.build_analyzer()(text1))
    grams2 = set(vec.build_analyzer()(text2))
    common = grams1 & grams2
    coverage = len(common) / (len(grams1) + 1e-9)
    return list(common), coverage


def parse_doxygen_params(comment):
    """
    Parses a Doxygen comment string and extracts parameter names and their descriptions.
    """
    params = {}
    # Regex to find @param <name> <description>
    pattern = re.compile(r'@param\s+([^\s]+)\s+(.*?)(?=\s*@param|\s*$)', re.DOTALL)
    matches = pattern.findall(comment)
    for match in matches:
        param_name = match[0]
        param_desc = match[1].strip()
        params[param_name] = param_desc
    return params

def compute_tag_f1(gt_list, llm_list):
    """
    Compute Tag-level F1 (structural correctness) for parameter tags.
    True Positive (TP): LLM param counts that match with GT param count 
    False Positive (FP): extra params generated by LLM beyond GT
    False Negative (FN): missing params that GT has but LLM didn't document
    """

    import pandas as pd
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)

    def norm_names(x):
        # normalize: lowercase and strip, excuse small difference like case change in llm output
        return set(n.strip().lower() for n in (x or []) if n and n.strip())

    gt_df = pd.DataFrame(gt_list)
    llm_df = pd.DataFrame(llm_list)
    merged = gt_df.merge(llm_df, on="function", suffixes=("_gt", "_llm"))

    #print(f'MERGEDF \n{merged}')
    tp, fp, fn = 0, 0, 0
    for _, row in merged.iterrows():

        gt_names  = norm_names(row.get("arg_var_names_gt", []))
        llm_names = norm_names(row.get("arg_var_names_llm", []))

        # params via name match 
        inter = gt_names & llm_names
        tp += len(inter)
        fp += len(llm_names - gt_names)
        fn += len(gt_names - llm_names)

        #print("FALSE POSITIVE", llm_names - gt_names)

        # return match
        gt_ret  = 1 if row.return_count_gt  > 0 else 0
        llm_ret = 1 if row.return_count_llm > 0 else 0

        if gt_ret == 1 and llm_ret == 1:
            # TP: return documented when required
            tp += 1                         
        elif gt_ret == 0 and llm_ret == 1:
            # FP: spurious @return
            fp += 1                         
            #print("FALSE POSITIVE", gt_ret, llm_ret)
        elif gt_ret == 1 and llm_ret == 0:
            # FN: missing required @return
            fn += 1                         

    precision = tp / (tp + fp + 1e-9)
    recall    = tp / (tp + fn + 1e-9)
    f1        = 2 * precision * recall / (precision + recall + 1e-9)

    print(f"TP={tp}, FP={fp}, FN={fn}, {precision}, {recall}, {f1}")
    return {"precision": precision, "recall": recall, "F1": f1}


def add_rag(query: str, persist_db: str):

    text_embeddings = get_text_embeddings()
    code_embeddings = get_code_embeddings()

    # Compute query vector (user_prompt + code) embedding
    #query_vec = np.array(text_embeddings.embed_query(query))
    #query_vec = query_vec / np.linalg.norm(query_vec)
    #print("QUERYVEC", query_vec)

    db_code = Chroma(persist_directory=persist_db, 
            embedding_function=code_embeddings, 
            collection_name="code_collection", 
            collection_metadata={"hnsw:space": "cosine"},
            client_settings=CHROMA_SETTINGS
            )
    db_text = Chroma(persist_directory=persist_db, 
            embedding_function=text_embeddings, 
            collection_name="text_collection",
            client_settings=CHROMA_SETTINGS
            )
    dbget_code = db_code.get() 
    dbget_text = db_text.get() 

    file_names = [meta["source"] for meta in dbget_code["metadatas"] if "source" in meta]
    print(persist_db, "NUM CODE DOCS in DB", len(file_names), flush=True)
    file_names = [meta["source"] for meta in dbget_text["metadatas"] if "source" in meta]
    print(persist_db, "NUM TEXT DOCS in DB", len(file_names), flush=True)

    # Retrieve documents along with their similarity scores
    num_text_ret = NUM_TEXT
    num_code_ret = NUM_CODE
    retriever_text = db_text.as_retriever(search_type="similarity", search_kwargs={"k": num_text_ret})  
    retriever_code = db_code.as_retriever(search_type="similarity", search_kwargs={"k": num_code_ret})  
    retrieved_docs = retriever_text.get_relevant_documents(query)
    retrieved_code = retriever_code.get_relevant_documents(query)

    retrieved_docs = retrieved_code + retrieved_docs
    #print(retrieved_docs)
    #for i, doc in enumerate(retrieved_docs, 1):
    #    retrieved_string = f"{doc.metadata['source']}:{doc.page_content[0:100]}"
    #    page_content = doc.page_content
    #    page_content_vec = np.array(text_embeddings.embed_query(page_content))
    #    page_content_vec = page_content_vec/np.linalg.norm(page_content_vec)
    #    sims = np.dot(page_content_vec, query_vec)
    #    print(f'{retrieved_string} -> {sims}')

    context_str = "\n\n".join(d.page_content for d in retrieved_docs)
    prompt_text = f"""
Context:
- {context_str}

**The above text is the context retrieved from the RAG sources. Based on the above context, generate doxygen style comments only for the function that is given below. Do not write comments for code in the retrieved context, but use it to inform the doxygen style comment.**

Question: {query}
"""
    return prompt_text

def query_llm_server(query: str):

    text_embeddings = get_text_embeddings()
    code_embeddings = get_code_embeddings()

    if RAG:
        prompt_text = add_rag(query, "/home/atif/celloai-dev/DB_fcs_cuda/")
    else:
        prompt_text = query

    messages = [{"role": "system", "content": doxygen_system_prompt}]
    messages.append({"role": "user", "content": prompt_text})
    nonstream_fn = openai_nonstream
   
    #print("**PROMPT_TEXT", prompt_text)
    payload = {
        "messages": messages,
        "max_tokens": MAX_TOKENS,
        "temperature": TEMPERATURE,
    }
    text, latency, ttft, tokens = nonstream_fn(url, payload)
    
    response_start = text.find(pattern) + len(pattern)
    response_rag = text[response_start:]
    response_rag_vec = np.array(text_embeddings.embed_query(response_rag))
    response_rag_vec = response_rag_vec / np.linalg.norm(response_rag_vec)

    print("**RESPONSE FULL", text)
    print("**RESPONSE", response_rag)
    
    return response_rag


def rewrite_file_with_comments_doc_stats(functions, file_path, prompt, llm_server=False): 

    import os, re

    doc_stats = []  # collect (function_name, param_count, return_count)
    function_name_comment = []

    if len(functions) > 0:
        file_path_comments = file_path + ".comments.cxx"
        print(f'Generating comments for {len(functions)} functions in {file_path}', flush=True)

        functions_first_line = []
        for function in functions:
            newline_index = function.index('\n')
            line = function[:newline_index]
            functions_first_line.append(line)

        idx = 0
        try:
            with open(file_path, 'r', encoding="latin-1") as source_file:
                with open(file_path_comments, 'w', encoding="utf-8") as destination_file:
                    for line in source_file:
                        if len(functions_first_line) > 0:
                            if idx == len(functions_first_line):
                                destination_file.write(line)
                            else:
                                if line.strip() == functions_first_line[idx].strip():
                                    query = prompt + functions[idx]
                                    if llm_server:
                                        answer = query_llm_server(query)
                                    else:
                                        print("Use LLM server with --llamacpp_server")
                                    destination_file.write("/**\n")
                                    clean_answer = remove_comment_block_init_end(answer)
                                    destination_file.write(clean_answer)
                                    destination_file.write(f"* This comment was generated by openai/gpt-oss-120b at temperature {TEMPERATURE}.\n")
                                    destination_file.write("*/ \n")
                                    destination_file.write(line)

                                    # collect stats from clean_answer + signature line
                                    var_names = re.findall(r'@param\s+([\w:]+)', clean_answer)
                                    param_count  = len(re.findall(r'@param\b', clean_answer))
                                    return_count = len(re.findall(r'@return\b', clean_answer))
                                    # Extract the value immediately after @return
                                    return_val = re.search(r'@return\s+(\w+)', clean_answer)

                                    if return_val:
                                        ret_val = return_val.group(1).strip()
                                        if ret_val.lower() in ("void", "none"):
                                            return_count = 0

                                    m = re.search(r'([~\w:<>]+)\s*\(', functions[idx])  # function name from signature line
                                    fname = m.group(1) if m else f"func_{idx}"
                                    doc_stats.append({
                                        "function": fname,
                                        "param_count": param_count,
                                        "arg_var_names": var_names,
                                        "return_count": return_count
                                    })
                                    
                                    function_name_comment.append({
                                        "function": fname,
                                        "comment": clean_answer 
                                    })
                                    print(f'Function {idx}: {line} Done', flush=True)
                                    idx = idx + 1
                                else:
                                    destination_file.write(line)
                        else:
                            destination_file.write(line)

        except FileNotFoundError:
            print(f"Error: The file {c_file_path} was not found.")
        except IOError as e:
            print(f"Error: An I/O error occurred. {e}")

        os.rename(file_path_comments, file_path)

        # Write function name comments in json to process later
        import json
        json_output_path = "comments.json"
        existing = []
        if os.path.exists(json_output_path):
            try:
                with open(json_output_path, "r", encoding="utf-8") as jf:
                    existing = json.load(jf)
            except Exception:
                existing = []

        combined = existing + function_name_comment
        with open(json_output_path, "w", encoding="utf-8") as jf:
            json.dump(combined, jf, ensure_ascii=False, indent=2)
            print(f"Function-comment JSON written to {json_output_path}", flush=True)

        return doc_stats  # <- return the collected list
    else:
        print(f'No functions captured.', flush=True)
        return doc_stats


@click.command()
@click.option(
    "--device_type",
    default="cuda" if torch.cuda.is_available() else "cpu",
    type=click.Choice(
        [
            "cpu",
            "cuda",
            "ipu",
            "xpu",
            "mkldnn",
            "opengl",
            "opencl",
            "ideep",
            "hip",
            "ve",
            "fpga",
            "ort",
            "xla",
            "lazy",
            "vulkan",
            "mps",
            "meta",
            "hpu",
            "mtia",
        ],
    ),
    help="Device to run on. (Default is cuda)",
)
@click.option(
    "--llamacpp_server",
    is_flag=True,
    help="Use LlamaCpp Servers for inference (Default is False)",
)


def main(device_type, llamacpp_server):

    logging.info(f"Running on: {device_type}")
 
    text_embeddings = get_text_embeddings()

    # # # # # # # # # # #
    # Code documentation
    # # # # # # # # # # #
 
    file_extensions = [".cxx", ".cpp", ".cc", ".tcc", ".cu"]
    head_extensions = [".h", ".hpp", ".hh", ".H"]

    #qa = retrieval_qa_pipline_with_logging(device_type, False , promptTemplate_type=model_type, temperature=temperature, chatbot=False)
 
    print("# "*10, "\n# Coverage score\n#", "# "*10)
    # # # # # # # # # # #
    # Coverage score: Generate function level Doxygen style comments
    # # # # # # # # # # #
    dir_home = r'./data/FastCaloGpu_temp/src/'
    list_all_files = []
    # search all source files inside a specific folder
    for ext in file_extensions:
        dir_path = dir_home+fr'/**/*{ext}'
        for file in glob.glob(dir_path, recursive=True):
            if file.endswith(".cxx.comments.cxx"):
                continue
            list_all_files.append(file)
    num_files = len(list_all_files)
    print(f"List of {num_files} files {list_all_files}")
  
    mean_precision, mean_recall, mean_f1 = 0., 0., 0.
    for file_path in list_all_files:

        function_names_params_returns = extract_cpp_function_names_params_returns(file_path)
        #print(function_names_params_returns)

        functions = extract_cpp_functions(file_path)
        #print(functions)
        #rewrite_file_with_comments(functions, file_path, doxygen_class_prompt, qa, temperature, llamacpp_server)
        doc_stats = rewrite_file_with_comments_doc_stats(functions, file_path, doxygen_function_prompt, llamacpp_server)
        
        print("GT", function_names_params_returns)
        print("LLM", doc_stats)

        if function_names_params_returns:
            f1_scores = compute_tag_f1(function_names_params_returns, doc_stats)
            mean_precision += f1_scores["precision"]
            mean_recall    += f1_scores["recall"]
            mean_f1        += f1_scores["F1"]
            #print(f'{f1_scores["precision"]}, {f1_scores["recall"]}, {f1_scores["F1"]}')
    
    mean_precision = mean_precision/num_files
    mean_recall    = mean_recall/num_files
    mean_f1        = mean_f1/num_files

    print("# "*10, "\n# Semantic differential score\n#","# "*10)
    # # # # # # # # # # # # # # # 
    # Semantic differential score
    # # # # # # # # # # # # # # #
    dir_path = "/home/atif/celloai-dev/SOURCE_DOCUMENTS_fcs_cuda/FastCaloSimAnalyzer"
    doxygen_html_path = os.path.join(dir_path,"html")
    json_path = os.path.join(doxygen_html_path,"merged_graph.json")
    import json
    with open(json_path, "r") as f:
        codebase_callgraph = json.load(f)
 
    graph = load_function_graph(json_path)

    with open("comments.json", "r") as f:
        fname_comments_json = json.load(f)
    
    function_names = [func['function'] for func in fname_comments_json]
    #print(function_names)
    comments_dict = {func['function']: func['comment'] for func in fname_comments_json}
    #print(comments_dict)

    count_common = 0
    sum_similarity = 0.
    
    for func in fname_comments_json:
        #print(func['function'], "AAA" , func['comment'])
        function_name = func['function']
        function_comment = func['comment']
        relationships = get_function_relationships(function_name, graph)
        #function_name = relationships[0]["name"]
        #print(function_name, relationships[0], "\n-_-_-_-_-_-_-\n")
        #print(f"Analyzing {function_name} with comment \n {function_comment}")
        
        if not relationships:
            continue

        # First loop over each caller and find common params
        for caller_name_full in relationships[0]["called_by"]:
            print(function_name, "is called by", caller_name_full)
            
            caller_name = caller_name_full.split('::')[-1]

            if caller_name == function_name:
                continue

            if caller_name in comments_dict:
                caller_comment = comments_dict[caller_name]
                #print(f"{caller_name} has comment \n {caller_comment}")
    
                # Parse params from both function and caller
                func_params = parse_doxygen_params(function_comment)
                caller_params = parse_doxygen_params(caller_comment)
    
                # Find common parameters
                common_params = set(func_params.keys()) & set(caller_params.keys())
    
                if common_params:
                    print(f"  Found common parameters between '{function_name}' and '{caller_name}':")
                    for param in common_params:
                        print(f"    Parameter: {param}")
                        print(f"      Comment in {function_name}: {func_params[param]}")
                        print(f"      Comment in {caller_name}: {caller_params[param]}")
                        
                        func_comm = func_params[param]
                        caller_comm = caller_params[param]
                        common, cov = common_ngrams(func_comm, caller_comm, n=1)
                        #print("Common n-grams:", common)
                        #print("Coverage:", cov)

                        func_comm_vec = np.array(text_embeddings.embed_query(func_comm))
                        func_comm_vec = func_comm_vec / np.linalg.norm(func_comm_vec)
                        caller_comm_vec = np.array(text_embeddings.embed_query(caller_comm))
                        caller_comm_vec = caller_comm_vec / np.linalg.norm(caller_comm_vec)
                        sum_similarity += np.dot(caller_comm_vec, func_comm_vec)
                        count_common = count_common + 1
                        print(f'Sim : {np.dot(caller_comm_vec, func_comm_vec)}')

                else:
                    print("  No common parameters found.")
            else:
                print(f"  Caller '{caller_name}' not found in comments.json.")
        print("-" * 20)

    if count_common and list_all_files:
        print(f'Mean P/R/F1 {mean_precision}, {mean_recall}, {mean_f1}, Mean similarity {sum_similarity/count_common}')
    elif count_common and not list_all_files:
        print(f'Mean P/R/F1 -, {mean_f1}, Mean similarity {sum_similarity/count_common}')
    elif not count_common and list_all_files:
        print(f'Mean P/R/F1 {mean_precision}, {mean_recall}, {mean_f1}, Mean similarity - ')
    else:
        print("No files or common params")



    print("# "*10, "\n# Athena code semantic similarity\n#", "# "*10)
    # # # # # # # # # # # # # # # # # 
    # Athena code semantic similarity
    # # # # # # # # # # # # # # # # # 
    dir_home  = r'./data/athena_expert_comments/Calorimeter/CaloClusterCorrection/src_no_comments/'
    json_path = r'./data/athena_expert_comments/comments.json'
    import json
    with open(json_path, "r") as f:
        expert_comments = json.load(f)

    list_all_files = []
    # search all source files inside a specific folder
    for ext in file_extensions:
        dir_path = dir_home+fr'/**/*{ext}'
        for file in glob.glob(dir_path, recursive=True):
            list_all_files.append(file)
    #print("List of all files", list_all_files)
  
    count = 0
    sum_similarity_athena = 0.
    for file_path in list_all_files:

        functions = extract_cpp_functions(file_path)
        #print(functions)
        
        for function in functions:
            query = doxygen_function_prompt + function
      
            newline_index = function.index('\n')
            first_line = function[:newline_index]
            #print(first_line) 
   
            nonstream_fn = openai_nonstream

            if RAG:
                prompt_text = add_rag(query, "/home/atif/celloai-dev/DB_athena_whole/")
            else:
                prompt_text = query
       
            pattern = "<|start|>assistant<|channel|>final<|message|>"
            messages = [{"role": "system", "content": doxygen_system_prompt}]
            messages.append({"role": "user", "content": prompt_text})
            url = f"http://{HOST}:{PORT}/v1/chat/completions"
            payload = {
                "messages": messages,
                "max_tokens": MAX_TOKENS,
                "temperature": TEMPERATURE,
                "stream": False,
            }
            text_norag, latency, ttft, tokens = openai_nonstream(url, payload)
            response_start = text_norag.find(pattern) + len(pattern)
            response_norag = text_norag[response_start:]

            #print(response_norag)
            for exp_comm in expert_comments:
                if exp_comm['function'] == first_line:
                    #print(exp_comm['comment'], "\n", "-*"*20)

                    llm_comm_vec = np.array(text_embeddings.embed_query(response_norag))
                    llm_comm_vec = llm_comm_vec / np.linalg.norm(llm_comm_vec)
                    exp_comm_vec = np.array(text_embeddings.embed_query(exp_comm['comment']))
                    exp_comm_vec = exp_comm_vec / np.linalg.norm(exp_comm_vec)
                    sum_similarity_athena += np.dot(llm_comm_vec, exp_comm_vec)
                    count = count + 1

    print("LLM <-> Expert similarity", sum_similarity_athena/count)

    print("FINAL SCORE")
    print(f'Mean P/R/F1 {mean_precision}, {mean_recall}, {mean_f1}, {sum_similarity/(count_common+1e-9)}, {sum_similarity_athena/(count+1e-9)}')



if __name__ == "__main__":
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(filename)s:%(lineno)s - %(message)s", level=logging.INFO
    )
    main()

